// Client to Server
export enum ServerCodes {
    INIT = "i",
    STATUS = "s",
    ROLL = "r",
    MESSAGE = "m",
    STOP_TURN = "t",
    BUY_DEVCARD = "bd",
    BUY_ROAD = "br",
    BUY_SETTLEMENT = "bs",
    BUY_CITY = "bc",
    MOVE_ROBBER = "mr",
    DROP_MATS = "dp",
    DEV_YEAROFPLENTY = "dyop",
    DEV_MONOPOL = "dm",
    DEV_ROADS = "dr",
    REQUEST_TRADES = "rt",
    APPLY_TRADE = "at",
}
// Server to Client
export enum ClientCodes {
    STATUS = "s",
    INIT = "i",
    TURN_DICE = "t",
    MESSAGE = "m",
    TURN_SWITCH = "a",
    PLAYER_UPDATE = "pu",
    BANK_UPDATE = "bu",
    OTHER_UPDATE = "ou",
    ACHIVEMENTS_UPDATE = "ao",
    MOVE_ROBBER = "mr",
    DEV_MONOPOL = "dm",
    WIN = "w",
    MATS_NOTIFICATION = "mn",
    GET_TRADES = "gt",
}
